function renderAll(){
 const inv=state.sourceType==='invoicePdf';
 $('accountIco').value=state.customerIco||''; $('docDate').value=state.date||''; $('deliveryDate').value=state.deliveryDate||state.dateTax||''; $('headerText').value=state.headerText||defaultHeader(state);
 ['invoiceFields','orderFields'].forEach(id=>{const e=$(id);if(e)e.style.display=(id==='invoiceFields')==(inv)?'grid':'none'});
 if(inv){$('invoiceNumber').value=state.invoiceNumber||state.dispatchNo||'';$('symVar').value=state.symVar||'';$('dateTax').value=state.dateTax||'';$('dateDue').value=state.dateDue||'';$('contractCode').value=state.contractCode||'';}
 const typeLabel=inv?'PDF prijatá faktúra':state.sourceType==='xlsx'?'Excel príloha ponuky':state.sourceType==='pdf'?'PDF ponuka':state.sourceType==='xml'?'XML výdajka Ptáček':'—';
 $('meta').innerHTML=[['Typ zdroja',typeLabel],['Súbor',state.sourceFile],['Číslo dokladu',state.invoiceNumber||state.dispatchNo],['Dodávateľ',state.supplier?.company||'—'],['Dátum',state.date],['Položky',state.items.length]].map(([a,b])=>`<div><small>${esc(a)}</small><b>${esc(b||'—')}</b></div>`).join(''); renderRows(); refresh();
}
function renderRows(){
 const tbody=$('items'); tbody.innerHTML=state.items.map((it,i)=>{const [cl,tx]=mappingStatus(it);return `<tr data-i="${i}"><td><input class="inc" type="checkbox" ${it.include?'checked':''}></td><td class="sourcecode">${esc(it.lineNo)}</td><td class="sourcecode">${esc(it.ptacekNo||'—')}</td><td class="sourcecode">${esc(it.vendorCode||'—')}</td><td class="codecol"><input class="pcode code" value="${esc(it.pohodaCode||'')}"></td><td><span class="tag ${cl}">${tx}</span></td><td class="desc"><input class="descInput" value="${esc(it.description)}" readonly></td><td class="smallcol"><input class="qty num" type="number" min="0" step="any" value="${num(it.quantity)}"></td><td>${esc(it.unit)}</td><td class="num">${money(it.listUnitPrice)}</td><td class="smallcol"><input class="unitPrice num" type="number" min="0" step="any" value="${num(effectiveUnitPrice(it))}"></td><td class="num lineBase">${money(it.quantity*effectiveUnitPrice(it))}</td><td><select class="vat">${VAT_OPTIONS.map(v=>`<option value="${v.key}" ${v.key===it.vatKey?'selected':''}>${v.label}</option>`).join('')}</select></td></tr>`}).join('');
}
function effectiveUnitPrice(it){return $('priceSource').value==='list'&&state.sourceType==='xml'?it.listUnitPrice:it.netUnitPrice}
function syncControls(){state.customerIco=$('accountIco').value.trim();state.date=$('docDate').value;state.deliveryDate=$('deliveryDate').value;state.headerText=$('headerText').value.trim().slice(0,240);if(state.sourceType==='invoicePdf'){state.invoiceNumber=$('invoiceNumber').value.trim();state.dispatchNo=state.invoiceNumber;state.symVar=$('symVar').value.trim();state.dateTax=$('dateTax').value;state.dateDue=$('dateDue').value;state.contractCode=$('contractCode').value.trim()}}
function refresh(){syncControls();let base=0,vat=0;state.items.forEach((it,i)=>{if(!it.include)return;const line=it.quantity*effectiveUnitPrice(it);base+=line;vat+=line*vatRate(it.vatKey)/100;const tr=$('items').querySelector(`tr[data-i="${i}"]`);if(tr){tr.querySelector('.lineBase').textContent=money(line);const [cl,tx]=mappingStatus(it);tr.querySelector('.tag').className='tag '+cl;tr.querySelector('.tag').textContent=tx}});$('sumBase').textContent=money(base);$('sumVat').textContent=money(vat);$('sumGross').textContent=money(base+vat);
 const inv=state.sourceType==='invoicePdf',problems=[];if(!/^\d{6,15}$/.test(state.customerIco||''))problems.push('IČO účtovnej jednotky nie je správne.');const active=state.items.filter(x=>x.include);if(!active.length)problems.push('Nie je označená žiadna položka.');if(inv&&!state.invoiceNumber)problems.push('Chýba číslo dodávateľskej faktúry.');active.forEach((x,i)=>{if(!inv&&!x.pohodaCode.trim())problems.push(`Položka ${x.lineNo||i+1}: chýba kód POHODA.`);if(!(x.quantity>0))problems.push(`Položka ${x.lineNo||i+1}: množstvo musí byť väčšie ako 0.`)});
 const val=$('validation');if(problems.length){val.className='warning danger';val.innerHTML='<b>Pred exportom opravte:</b><br>'+problems.map(esc).join('<br>')}else{val.className='warning success';val.innerHTML=inv?'<b>Pripravené na export prijatej faktúry.</b> Položky bez Kódu POHODA sa vytvoria ako textové; položky s kódom ako skladové.':'<b>Pripravené na export.</b> POHODA vytvorí vydanú objednávku so skladovými položkami.'}
 $('download').disabled=!!problems.length;$('copy').disabled=!!problems.length;$('xmlPreview').value=problems.length?'':buildXml();const pw=$('priceWarning');pw.style.display='block';if(inv){pw.className='warning success';pw.innerHTML=`<b>Prijatá faktúra:</b> PDF uvádza základ ${money(state.baseTotal)} + DPH ${money(state.vatTotal)} = ${money(state.grossTotal)}. Pri zaokrúhlených J.cenách používame efektívnu cenu z riadkového základu, aby sedela suma faktúry.`}else if(state.sourceType==='xlsx'){pw.className='warning success';pw.innerHTML='<b>Excel:</b> ceny pred exportom skontrolujte.'}else if($('priceSource').value==='list'){pw.className='warning danger';pw.innerHTML='<b>Pozor:</b> používate cenníkovú cenu UnitPrice.'}else{pw.className='warning success';pw.innerHTML='<b>XML Ptáček:</b> jednotková nákupná cena = VATBaseAmount ÷ Quantity.'}
}
function buildXml(){if(state.sourceType==='invoicePdf')return buildReceivedInvoiceXml();syncControls();const id=safeId(state.dispatchNo),link=$('linkAddress').checked?' linkToAddress="true"':'',pay=$('paymentType').value.trim(),store=$('storeId').value.trim(),ignore=$('ignoreStoreFilter').checked?' applyUserSettingsFilterOnTheStore="false"':'';const items=state.items.filter(x=>x.include).map(it=>`\t\t\t<ord:orderItem>\n\t\t\t\t<ord:quantity>${num(it.quantity)}</ord:quantity>\n\t\t\t\t<ord:delivered>0</ord:delivered>\n\t\t\t\t<ord:rateVAT>${it.vatKey}</ord:rateVAT>\n\t\t\t\t<ord:homeCurrency><typ:unitPrice>${num(effectiveUnitPrice(it))}</typ:unitPrice></ord:homeCurrency>\n\t\t\t\t<ord:stockItem${ignore}>${store?`<typ:store><typ:ids>${esc(store)}</typ:ids></typ:store>`:''}<typ:stockItem><typ:ids>${esc(it.pohodaCode.trim())}</typ:ids></typ:stockItem></ord:stockItem>\n\t\t\t</ord:orderItem>`).join('\n');return `<?xml version="1.0" encoding="UTF-8"?>\n<dat:dataPack id="PT-${esc(id)}" ico="${esc(state.customerIco)}" application="Spektra-Ptacek-v3.0" version="2.0" xmlns:dat="http://www.stormware.cz/schema/version_2/data.xsd" xmlns:ord="http://www.stormware.cz/schema/version_2/order.xsd" xmlns:typ="http://www.stormware.cz/schema/version_2/type.xsd"><dat:dataPackItem id="${esc(id)}" version="2.0"><ord:order version="2.0"><ord:orderHeader><ord:orderType>issuedOrder</ord:orderType><ord:date>${esc(state.date)}</ord:date><ord:dateDelivery>${esc(state.deliveryDate)}</ord:dateDelivery><ord:text>${esc(state.headerText)}</ord:text><ord:partnerIdentity><typ:address${link}><typ:company>${esc(state.supplier.company)}</typ:company><typ:city>${esc(state.supplier.city)}</typ:city><typ:street>${esc(state.supplier.street)}</typ:street><typ:zip>${esc(state.supplier.zip)}</typ:zip><typ:ico>${esc(state.supplier.ico)}</typ:ico><typ:dic>${esc(state.supplier.dic)}</typ:dic></typ:address></ord:partnerIdentity>${pay?`<ord:paymentType><typ:ids>${esc(pay)}</typ:ids></ord:paymentType>`:''}</ord:orderHeader><ord:orderDetail>\n${items}\n</ord:orderDetail><ord:orderSummary><ord:roundingDocument>math2one</ord:roundingDocument></ord:orderSummary></ord:order></dat:dataPackItem></dat:dataPack>`}
