function renderAll(){
 $('accountIco').value=state.customerIco||''; $('docDate').value=state.date||''; $('deliveryDate').value=state.deliveryDate||''; $('headerText').value=state.headerText||defaultHeader(state);
 $('meta').innerHTML=[['Typ zdroja',state.sourceType==='xlsx'?'Excel príloha ponuky':state.sourceType==='xml'?'XML výdajka Ptáček':'—'],['Súbor',state.sourceFile],['Číslo dokladu',state.dispatchNo],['Objednávka Ptáček',state.supplierOrderNo||'—'],['Dátum',state.date],['Položky',state.items.length]].map(([a,b])=>`<div><small>${esc(a)}</small><b>${esc(b||'—')}</b></div>`).join('');
 renderRows(); refresh();
}
function renderRows(){
 const tbody=$('items'); tbody.innerHTML=state.items.map((it,i)=>{ const [cl,tx]=mappingStatus(it); return `<tr data-i="${i}">
 <td><input class="inc" type="checkbox" ${it.include?'checked':''}></td><td class="sourcecode">${esc(it.lineNo)}</td><td class="sourcecode">${esc(it.ptacekNo||'—')}</td><td class="sourcecode">${esc(it.vendorCode)}</td>
 <td class="codecol"><input class="pcode code" value="${esc(it.pohodaCode)}"></td><td><span class="tag ${cl}">${tx}</span></td>
 <td class="desc"><input class="descInput" value="${esc(it.description)}" readonly title="Kontrolný popis zo zdrojového dokladu; do XML sa pri skladovej položke neprenáša."></td><td class="smallcol"><input class="qty num" type="number" min="0" step="any" value="${num(it.quantity)}"></td><td>${esc(it.unit)}</td>
 <td class="num">${state.sourceType==='xlsx'?'—':money(it.listUnitPrice)}</td><td class="smallcol"><input class="unitPrice num" type="number" min="0" step="any" value="${num(effectiveUnitPrice(it))}"></td><td class="num lineBase">${money(it.quantity*effectiveUnitPrice(it))}</td>
 <td><select class="vat">${VAT_OPTIONS.map(v=>`<option value="${v.key}" ${v.key===it.vatKey?'selected':''}>${v.label}</option>`).join('')}</select></td></tr>`; }).join('');
}
function effectiveUnitPrice(it){ return $('priceSource').value==='list'&&state.sourceType==='xml'?it.listUnitPrice:it.netUnitPrice; }
function syncControls(){ state.customerIco=$('accountIco').value.trim(); state.date=$('docDate').value; state.deliveryDate=$('deliveryDate').value; state.headerText=$('headerText').value.trim().slice(0,240); }
function refresh(){ syncControls(); let base=0,vat=0; state.items.forEach((it,i)=>{ if(!it.include)return; const line=it.quantity*effectiveUnitPrice(it); base+=line; vat+=line*vatRate(it.vatKey)/100; const tr=$('items').querySelector(`tr[data-i="${i}"]`); if(tr){tr.querySelector('.lineBase').textContent=money(line); const [cl,tx]=mappingStatus(it); tr.querySelector('.tag').className='tag '+cl; tr.querySelector('.tag').textContent=tx;}}); $('sumBase').textContent=money(base); $('sumVat').textContent=money(vat); $('sumGross').textContent=money(base+vat);
 const problems=[]; if(!/^\d{6,15}$/.test(state.customerIco||''))problems.push('IČO účtovnej jednotky nie je vyplnené správne.'); const active=state.items.filter(x=>x.include); if(!active.length)problems.push('Nie je označená žiadna položka.'); active.forEach((x,i)=>{if(!x.pohodaCode.trim())problems.push(`Položka ${x.lineNo||i+1}: chýba kód POHODA.`);if(!(x.quantity>0))problems.push(`Položka ${x.lineNo||i+1}: množstvo musí byť väčšie ako 0.`);if(effectiveUnitPrice(x)<0)problems.push(`Položka ${x.lineNo||i+1}: cena nemôže byť záporná.`)});
 const val=$('validation'); if(problems.length){val.className='warning danger';val.innerHTML='<b>Pred exportom opravte:</b><br>'+problems.map(esc).join('<br>');}else{val.className='warning success';val.innerHTML='<b>Pripravené na export.</b> POHODA vytvorí vydanú objednávku so skladovými položkami, s hodnotou Dodané = 0 a názvy prevezme zo skladových kariet.';}
 $('download').disabled=!!problems.length; $('copy').disabled=!!problems.length; $('xmlPreview').value=problems.length?'':buildXml();
 const pw=$('priceWarning'); pw.style.display='block';
 if(state.sourceType==='xlsx'){pw.className='warning success';pw.innerHTML='<b>Excel:</b> jednotková cena sa načítala zo stĺpca J.cena a DPH zo stĺpca %DPH. Pred exportom ceny skontrolujte, pretože príloha ponuky môže obsahovať predajné, nie nákupné ceny.';}
 else if($('priceSource').value==='list'){pw.className='warning danger';pw.innerHTML='<b>Pozor:</b> používate cenníkovú cenu UnitPrice. Vo výdajke Ptáčka je skutočný základ po zľave v poli VATBaseAmount; príjemka by preto mohla mať nesprávnu obstarávaciu cenu.';}
 else{pw.className='warning success';pw.innerHTML='<b>XML Ptáček:</b> jednotková nákupná cena = VATBaseAmount ÷ Quantity. Tým sa zachová základ DPH z výdajky.';}
}
function buildXml(){ syncControls(); const id=safeId(state.dispatchNo); const link=$('linkAddress').checked?' linkToAddress="true"':''; const pay=$('paymentType').value.trim(); const store=$('storeId').value.trim(); const ignore=$('ignoreStoreFilter').checked?' applyUserSettingsFilterOnTheStore="false"':'';
 const items=state.items.filter(x=>x.include).map(it=>`\t\t\t<ord:orderItem>\n\t\t\t\t<ord:quantity>${num(it.quantity)}</ord:quantity>\n\t\t\t\t<ord:delivered>0</ord:delivered>\n\t\t\t\t<ord:rateVAT>${it.vatKey}</ord:rateVAT>\n\t\t\t\t<ord:homeCurrency>\n\t\t\t\t\t<typ:unitPrice>${num(effectiveUnitPrice(it))}</typ:unitPrice>\n\t\t\t\t</ord:homeCurrency>\n\t\t\t\t<ord:stockItem${ignore}>\n${store?`\t\t\t\t\t<typ:store>\n\t\t\t\t\t\t<typ:ids>${esc(store)}</typ:ids>\n\t\t\t\t\t</typ:store>\n`:''}\t\t\t\t\t<typ:stockItem>\n\t\t\t\t\t\t<typ:ids>${esc(it.pohodaCode.trim())}</typ:ids>\n\t\t\t\t\t</typ:stockItem>\n\t\t\t\t</ord:stockItem>\n\t\t\t</ord:orderItem>`).join('\n');
 return `<?xml version="1.0" encoding="UTF-8"?>\n<dat:dataPack id="PT-${esc(id)}" ico="${esc(state.customerIco)}" application="Spektra-Ptacek-v2.2" version="2.0" note="Import vydanej objednávky zo zdrojového dokladu"\n xmlns:dat="http://www.stormware.cz/schema/version_2/data.xsd"\n xmlns:ord="http://www.stormware.cz/schema/version_2/order.xsd"\n xmlns:typ="http://www.stormware.cz/schema/version_2/type.xsd">\n\t<dat:dataPackItem id="${esc(id)}" version="2.0">\n\t\t<ord:order version="2.0">\n\t\t\t<ord:orderHeader>\n\t\t\t\t<ord:orderType>issuedOrder</ord:orderType>\n\t\t\t\t<ord:date>${esc(state.date)}</ord:date>\n\t\t\t\t<ord:dateDelivery>${esc(state.deliveryDate)}</ord:dateDelivery>\n\t\t\t\t<ord:text>${esc(state.headerText)}</ord:text>\n\t\t\t\t<ord:partnerIdentity>\n\t\t\t\t\t<typ:address${link}>\n\t\t\t\t\t\t<typ:company>${esc(state.supplier.company)}</typ:company>\n\t\t\t\t\t\t<typ:city>${esc(state.supplier.city)}</typ:city>\n\t\t\t\t\t\t<typ:street>${esc(state.supplier.street)}</typ:street>\n\t\t\t\t\t\t<typ:zip>${esc(state.supplier.zip)}</typ:zip>\n\t\t\t\t\t\t<typ:ico>${esc(state.supplier.ico)}</typ:ico>\n\t\t\t\t\t\t<typ:dic>${esc(state.supplier.dic)}</typ:dic>\n\t\t\t\t\t</typ:address>\n\t\t\t\t</ord:partnerIdentity>\n${pay?`\t\t\t\t<ord:paymentType>\n\t\t\t\t\t<typ:ids>${esc(pay)}</typ:ids>\n\t\t\t\t</ord:paymentType>\n`:''}\t\t\t</ord:orderHeader>\n\t\t\t<ord:orderDetail>\n${items}\n\t\t\t</ord:orderDetail>\n\t\t\t<ord:orderSummary>\n\t\t\t\t<ord:roundingDocument>math2one</ord:roundingDocument>\n\t\t\t</ord:orderSummary>\n\t\t</ord:order>\n\t</dat:dataPackItem>\n</dat:dataPack>\n`;
}
